[package]
name = "xtreme_game"
version = "0.1.0"
authors = ["Ilmari Autio <ilmari.autio@gmail.com>"]

[dependencies]
glium = "0.16.0"
libloading = "0.3.2"
cgmath = "0.14.1"

[lib]
crate-type = ["dylib"]
